### ISSUE TITLE
Proprietary or open source?

### ISSUE THREAD

**Issue by joergister** [flathub/org.jdownloader.JDownloader#1]
The Website http://jdownloader.org/ sais 

> JDownloader is a free, open-source download management tool

but you mark it as proprietary? Why that? 
I can see you didn't use the sources to build the flatpak, are they no available?  

If it really it a proprietary project, the description (on flathub) should be changed. Otherwise the license should be changed.

This way it doesn't quite make sense to users.

Or am I missing something really obvious?

**Comment by eszlari** [comment]
> I can see you didn't use the sources to build the flatpak, are they no available?

Parts of are not available.

fixed: https://github.com/flathub/org.jdownloader.JDownloader/commit/5aa005614b65cb6941c4695af52c5c0d3ed2c8db

**Comment by joergister** [comment]
ah ok, that makes it easier to understand. 
wow that was fast. thank you :+1:

**Comment by EchedeyLR** [comment]
Sorry but, exactly which parts? 

I don't see any reference in the source code repo references here https://svn.jdownloader.org/projects/jd

**Comment by eszlari** [comment]
It was a long time ago that I tried to compile it myself. Why don't try it and then we will see.

**Comment by EchedeyLR** [comment]
> It was a long time ago that I tried to compile it myself. Why don't you try it and then we will see.

I will try and report here.

**Comment by nahuelwexd** [comment]
Hi! I just wanted to comment that JDownloader is licensed under the GPLv3, and that its compilation instructions are publicly available here https://support.jdownloader.org/Knowledgebase/Article/View/setup-ide-eclipse.

I attach a screenshot where you can see that I have compiled it on my own.
![Captura desde 2022-04-02 16-54-08](https://user-images.githubusercontent.com/18204745/161399193-31608b89-9f9f-4eb3-9456-8b7ae23e5c55.png)

**Comment by EchedeyLR** [comment]
@eszlari Could you change the license now?

**Comment by EchedeyLR** [comment]
Relevant here: @barthalion and @KuSH

**Comment by KuSh** [comment]
At the moment the binary file bundled contains closed source software (at least JDClosed.jar and updater code), see for example discussion here https://github.com/NixOS/nixpkgs/pull/136998/files#r720173284

I'll try to see if I can compile it from source but information is scarce and I'm not sure it will be completely functional (I wasn't able to find with a rapid search what JDClosed.jar contained)

**Comment by jiaz83** [comment]
@KuSh Such a JDownloader build will be completely functional. JDClosed repository contains plugins of sites that like to play cat/mouse (we change plugin, they change site) and as such are not part of open source repositories to help with this situation. We can provide a delayed copy if wished but it only contains very few plugins anyway. JDownloaderServerOptions contains meta information for update system to know what OS/CPU/environment will receieve what files. UpdateClientV2 and JDownloaderUpdater contain the update client.
