### ISSUE TITLE
Video files not merge when finish.

### ISSUE THREAD

**Issue by AdsonCicilioti** [flathub/org.jdownloader.JDownloader#11]
Videos downloades return error on download list and file is splited as dashAdio and dashVideo formats.

![image](https://user-images.githubusercontent.com/6278398/52155194-a8aee800-2668-11e9-9b50-6f8c632ec37b.png)
This files is valids.. caontaining audio and video saparately.

I try set ffprobe in advanced settings but without success

**Comment by heipa0** [comment]
As a workaround I downloaded ffmpeg from here:
https://ffmpeg.org/download.html

Then extracted it to /home/username/.var/app/org.jdownloader.JDownloader/ffmpeg/

And then set the following options at the Advanced Settings:
![jdownloader](https://user-images.githubusercontent.com/35292661/61775508-a5cccd00-ae2b-11e9-95bc-b19cf2177c6e.png)

Now video merge works fine.

However this should be included in the flapak itself.

**Comment by Kishan0330** [comment]
i have alredy installed ffmpeg but it still do not merge

**Comment by serggiobarata** [comment]
Não encontrei o caminho da pasta .var no meu Windows 11.
