### ISSUE TITLE
include rar

### ISSUE THREAD

**Issue by fishxz** [flathub/org.jdownloader.JDownloader#13]
hey,
jdl depends on unrar to exctract rars, but it relies on the system to have it. so i think it would make sense to provide it in the pakage.

**Comment by fishxz** [comment]
well, sorry for that... i forgot to close this issue... i think jdownloader already comes with unrar.

**Comment by eszlari** [comment]
I could not find unrar in the JDownloader directory.

Is this implemented in Java?

**Comment by fishxz** [comment]
The problem was - if I remember right: on failed extraction attempt jdownloader was not able to extract again, by forcing it manually.
