### ISSUE TITLE
Right click > Open Download Directory no longer working

### ISSUE THREAD

**Issue by Mershl** [flathub/org.jdownloader.JDownloader#15]
The "Open Download Directory" stopped working last week. The button can be pressed but nothing is happening. No error message on the GUI nor log message on the terminal is visible.

Tested on a fresh installation of Fedora 33 (`nautilus-3.38.1-1`, `flatpak-1.8.2-2`).

`flatpak info`:
```
          ID: org.jdownloader.JDownloader
         Ref: app/org.jdownloader.JDownloader/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2.0
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 189,9 MB
     Runtime: org.freedesktop.Platform/x86_64/20.08
         Sdk: org.freedesktop.Sdk/x86_64/20.08

      Commit: c53cd444469b79926796f47e3ee31af816bf3bdacadd98dc6145d3ce0140e597
      Parent: b73679768b6af7ec2cce560cf6d4849daa9078dc72fba88f93bc1d86f70cac02
     Subject: freedesktop runtime 20.08 (e71e3de9)
        Date: 2020-10-04 23:44:16 +0000
```

**Comment by eszlari** [comment]
Does it work again if you revert it?

```
$ flatpak remote-info --log flathub org.jdownloader.JDownloader
$ flatpak update --commit=b73679768b6af7ec2cce560cf6d4849daa9078dc72fba88f93bc1d86f70cac02 org.jdownloader.JDownloader
```

Anything in `journalctl`?
Does it work in another DE?

**Comment by Mershl** [comment]
Tested it now with the versions from 2019 (`b73679768b6af7ec2cce560cf6d4849daa9078dc72fba88f93bc1d86f70cac02`) and 2018 (`d22a39817258a68b6b807d732f998f54a98b76e55b2a8d5ca713ada346277eba`) with several download file locations inside and outside of the home folder.

The feature is no longer working independent of the installed jDownloader deployment on Gnome 3.38.1.

At the moment I can only test it on Gnome 3.38.1 and `flatpak-1.8.2-2`.

**Comment by eszlari** [comment]
You could try another DE in a VM using https://flathub.org/apps/details/org.gnome.Boxes

**Comment by Mershl** [comment]
Might be an flatpak issue: https://github.com/flatpak/flatpak/issues/3879

**Comment by eszlari** [comment]
From reading this, I get that you will have to wait until they update `flatpak-xdg-utils` in the runtime:

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/release/20.08/NEWS

**Comment by Mershl** [comment]
Issue no longer reproduciable using flatpak and xdg-desktop-portal 1.12.1
