### ISSUE TITLE
OpenJDK 10 is now available

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.jdownloader.JDownloader#2]
The OpenJDK 10 extension is now available on Flathub. This may or may not improve things with JDownloader (I suspect it will, SSL support should be improved) but I wanted to let you know for your testing.

**Comment by eszlari** [comment]
https://github.com/flathub/org.jdownloader.JDownloader/commit/57206b226aa8a43143f956f9f88e88e590e57503
