### ISSUE TITLE
 Please allow access to `xdg-user-dir DOWNLOAD`

### ISSUE THREAD

**Issue by Tids** [flathub/org.jdownloader.JDownloader#3]
`xdg-user-dir DOWNLOAD` (Users Download folder) is important to have access to, because in there are the downloaded link containers and maybe other stuff.
Also some of us want to save our download from jdownloader in there $(xdg-user-dir DOWNLOAD)/jdownloader is my preffered directory.

Right now the flatpak is not usable for me because of this limitation

**Comment by TingPing** [comment]
> Right now the flatpak is not usable for me because of this limitation

You can always override permissions as you wish: `flatpak override --user --filesystem=xdg-download org.jdownloader.JDownloader
`

**Comment by Tids** [comment]
sure, but thats just a temporary solution. Nothing I'd like to do every time i want to use jdownloader. Is there a reason jdownloader does not use the standard download folder for downloads, or a subfolder inside the download folder?

**Comment by pizzadude** [comment]
@Tids Then edit the .desktop file (copy it to ~/.local/share/applications first, with same filename).

It should be in /var/lib/flatpak/exports/share/applications/

**Comment by eszlari** [comment]
>  Is there a reason jdownloader does not use the standard download folder for downloads, or a subfolder inside the download folder?

I just wanted to lock down JDownloader as much as possible, because I'm not sure, how trustworthy upstream is.

You could also create a link:

```
$ ln -sf /home/name/JDownloader /home/name/Downloads/JDownloader
```

**Comment by mati865** [comment]
By default JD put files into sandboxed `/home/name/Downloads` which is not exposed in any way.
I've already set download location to exposed `/home/name/JDownloader` but how can I access files already downloaded to old location?

**Comment by eszlari** [comment]
https://github.com/flathub/org.jdownloader.JDownloader/commit/f68d988a309ac60e60019430c7c15deb695e2432
