### ISSUE TITLE
Yells that tray isn't supported on first start

### ISSUE THREAD

**Issue by hadess** [flathub/org.jdownloader.JDownloader#4]
Instead of ignoring it.

**Comment by eszlari** [comment]
Well, here under KDE it doesn't. Maybe you are using the wrong DE? :smirk:

Anyway, I would say this is an upstream bug.

**Comment by hadess** [comment]
> Well, here under KDE it doesn't. Maybe you are using the wrong DE?

Super funny.

**Comment by eszlari** [comment]
Closing (upstream bug).
