### ISSUE TITLE
In which directory JDownloader store downloaded files

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.jdownloader.JDownloader#7]
In which directory JDownloader store downloaded files. I used it but were unable to find my downloaded files. There were a new directory auto created by Jdownloader but file was not in that directory. I tried with simple video and compressed files.

@nedrichards Could help? Topic: [https://community.endlessos.com/t/how-to-install-jdownloader-on-endless-os/7291/2](https://community.endlessos.com/t/how-to-install-jdownloader-on-endless-os/7291/2?u=leandrostanger)

**Comment by RyuzakiKK** [comment]
JDownloader has write access only to `~/JDownloader`.
So you need to go to Settings -> General -> Download Folder and be sure that it's set to `~/JDownloader`

**Comment by eszlari** [comment]
It's now the standard location: `~/Downloads`

See: https://github.com/flathub/org.jdownloader.JDownloader/commit/f68d988a309ac60e60019430c7c15deb695e2432
