### ISSUE TITLE
OpenJDK 11.0.1 is now available

### ISSUE THREAD

**Issue by mbooth101** [flathub/org.jdownloader.JDownloader#8]
Hi,

Thanks for being quick to update to OpenJDK 11, but it would be great if you could rebuild one more time against the latest build of the OpenJDK 11 extension.

I just updated it to 11.0.1 and it also includes an important SSL fix (for details see https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11/issues/2)

You can check the version your app contains by doing:
```
$ flatpak run --command=/app/jre/bin/java org.jdownloader.JDownloader -version
```
It should say 11.0.1

Thanks for your time,
Mat

**Comment by eszlari** [comment]
done: https://github.com/flathub/org.jdownloader.JDownloader/commit/4257cfa3a3c578428d2fc7c901003c48d192d6dd
